# Header
menu:
  首页: /
  文章: /archives
  GIT: https://github.com/HiServiceRD
rss: /atom.xml

# Content
excerpt_link: 查看详细
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-51090540-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: